# NUMPY - Numerical Python
> A Python Library used for working with arrays/matrices.
>> Numpy arrays are much faster(50x) than lists.



### To install numpy, use the following command
> pip install numpy

#### Topics to be covered:
1. Numpy Arrays, and converting a list/tuple/sets into arrays
2. Dimensions - 0D,1D,2D...
3. Accessing array elements, Negative Indexing
4. Slicing Arrays
5. Array Shape and Reshape
6. Unknown Dimenstion in Reshape
7. Flatenning any n-D Array
8. Joining Arrays, Stacking(horizontally and Vertically)
9. Where function and SearchSorted.
10. Some inbuilt NumPy Functions <b> (BONUS) </b> - sum,mean,median,std,var,unique,floor,ceil,arange,reciprocal,operations on arrays(+,-,*,/,%),power(constants and arrays),etc..

In [4]:
import numpy as np

In [5]:
myarray=np.array([1,2,3,4])
print(myarray,type(myarray))

[1 2 3 4] <class 'numpy.ndarray'>


In [6]:
#converting lists into array
mylist=[1,2,3,4]
myarray=np.array(mylist)
print(myarray,type(myarray))

[1 2 3 4] <class 'numpy.ndarray'>


In [7]:
#converting tuples into array
mytuple=(1,2,3,4)
myarray=np.array(mytuple)
print(myarray,type(myarray))

[1 2 3 4] <class 'numpy.ndarray'>


In [11]:
#converting sets into array
myset={1,2,3}
myarray=np.array(myset)
print(myarray,type(myarray))

{1, 2, 3} <class 'numpy.ndarray'>


In [12]:
#getting dimensions of a 0-dimensional array
arr0=np.array(20)
print(arr0)
print(arr0.ndim)

20
0


In [13]:
#getting dimensions of a 1-dimensional array
arr0=np.array([20,1,23])
print(arr0)
print(arr0.ndim)

[20  1 23]
1


In [18]:
#getting dimensions of a 3-dimensional array
arr0=np.array([[[20,1,23],[2,34,5]],[[20,12,29],[23,4,54]]])
print(arr0)
print(arr0.ndim)

[[[20  1 23]
  [ 2 34  5]]

 [[20 12 29]
  [23  4 54]]]
3


In [17]:
#positive indexing in arrays
arr0[0,1,2]

5

In [20]:
#negative indexing in arrays
arr0[-1,-2,-2]

12

# Day 2
4. Slicing Arrays
5. Array Shape and Reshape
6. Unknown Dimenstion in Reshape

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,43,5,6,7,8])
print(arr)

[ 1  2 43  5  6  7  8]


In [3]:
newarr=arr[2:5]
print(newarr)

[43  5  6]


In [6]:
# to slice an array: arr_name[start:end:step]
newarr=arr[:5]
print(newarr)

[ 1  2 43  5  6]


In [7]:
newarr=arr[1:]
print(newarr)

[ 2 43  5  6  7  8]


In [9]:
newarr=arr[1::2]
print(newarr)

[2 5 7]


In [15]:
arr2=np.array([[1,2],[5,6],[8,9]])
print(arr2)

[[1 2]
 [5 6]
 [8 9]]


In [13]:
newarr=arr2[1:]
print(newarr)

[[5 6 7]
 [8 9 4]]


In [18]:
print(arr2.shape[0])

3


In [19]:
print(newarr.shape[0])

2


In [29]:
arr3=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [30]:
arr3.reshape(4,-1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
arr4=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr4)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [34]:
arr4.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

# Day 3
7. Flatenning any n-D Array
8. Joining Arrays, Stacking(horizontally and Vertically)
9. Where function and SearchSorted.

In [1]:
import numpy as np

In [2]:
arr0=np.array([[[20,1,23],[2,34,5]],[[20,12,29],[23,4,54]]])
print(arr0)
print(arr0.ndim)

[[[20  1 23]
  [ 2 34  5]]

 [[20 12 29]
  [23  4 54]]]
3


In [3]:
arr0.reshape(-1)

array([20,  1, 23,  2, 34,  5, 20, 12, 29, 23,  4, 54])

In [6]:
arr1=np.array([1,2,3])
arr2=np.array([5,6,7])
arr=np.concatenate((arr1,arr2))
arr

array([1, 2, 3, 5, 6, 7])

In [9]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [12]:
arr1=np.array([1,2,3])
arr2=np.array([5,6,7])
arr=np.stack((arr1,arr2),axis=1)
arr

array([[1, 5],
       [2, 6],
       [3, 7]])

In [13]:
arr1=np.array([1,2,3])
arr2=np.array([5,6,7])
arr=np.hstack((arr1,arr2))
arr

array([1, 2, 3, 5, 6, 7])

In [14]:
arr1=np.array([1,2,3])
arr2=np.array([5,6,7])
arr=np.vstack((arr1,arr2))
arr

array([[1, 2, 3],
       [5, 6, 7]])

In [19]:
arr1=np.array([1,2,3,6,5,3,2,1])
indx=np.where(arr1==3)
print(indx)

(array([2, 5], dtype=int64),)


In [20]:
indx=np.where(arr1%2==0)
print(indx)

(array([1, 3, 6], dtype=int64),)


In [21]:
arr1=np.array([1,2,3,6,5,3,2,1])
arr1.sort()
arr1

array([1, 1, 2, 2, 3, 3, 5, 6])

In [26]:
x=np.searchsorted(arr1,3)
x

4

# Day 4
10. <b>Some inbuilt NumPy Functions</b> - unique,sum,mean,median,std,var,floor,ceil,arange,reciprocal,operations on arrays(+,-,*,/,%),power(constants and arrays),matmul,determinant,distance between points,matrix_rank,etc..

In [1]:
import numpy as np

In [6]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [7]:
np.unique(arr)

array([1, 2, 3, 4, 5])

In [8]:
np.sum(arr)

15

In [9]:
np.mean(arr)

3.0

In [10]:
np.median(arr)

3.0

In [11]:
np.std(arr)

1.4142135623730951

In [12]:
np.var(arr)

2.0

In [13]:
arr=np.array([1.2,2.9,3,4.5,5.4])
arr

array([1.2, 2.9, 3. , 4.5, 5.4])

In [15]:
np.floor(arr)

array([1., 2., 3., 4., 5.])

In [18]:
np.arange(3,9,2) #(start=0,end,step=1)

array([3, 5, 7])

In [21]:
arr=np.array([1.,2.,3.,4.,5.])
arr

array([1., 2., 3., 4., 5.])

In [22]:
np.reciprocal(arr)

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ])

In [28]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
np.remainder(arr2,arr1)

array([0, 1, 0], dtype=int32)

In [30]:
arr1=np.array([1,2,3])
arr1

array([1, 2, 3])

In [31]:
np.power(arr1,2)

array([1, 4, 9], dtype=int32)

In [32]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [33]:
np.power(arr1,arr2)

array([  1,  32, 729], dtype=int32)

In [38]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[4,5],[4,6]])

In [39]:
np.matmul(arr1,arr2)

array([[12, 17],
       [28, 39]])

In [40]:
np.linalg.det(arr1)

-2.0000000000000004

In [41]:
np.linalg.matrix_rank(arr1)

2

In [43]:
p1=np.array([1,2,3,4])
p2=np.array([2,4,5,6])
np.linalg.norm(p1-p2)

3.605551275463989